name: Build & Release

on:
  push:
    branches: [ master ]
    
env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
  AZURE_FUNCTIONAPP_NAME: 'bvdwalt-IncomeTax'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
        include-prerelease: true
    - name: Restore dependencies
      run: dotnet restore
    - name: Test
      run: dotnet test
    - name: Build
      run: dotnet build --no-restore --configuration Release --output ./output
    - name: Release To Azure Functions Action
      uses: Azure/functions-action@v1.4.0
      with:
        app-name: '${{ env.AZURE_FUNCTIONAPP_NAME }}'
        slot-name: 'production'
        package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
